### ISSUE TITLE
The link of model weights failure? 

### ISSUE THREAD

**Issue by xjcvip007** [HRNet/HRNet-Facial-Landmark-Detection#1]
Thanks for your wonderful jobs~ One question, your link to model weights failure, maybe some mistakes happened?

**Comment by wondervictor** [comment]
Can you access OneDrive with provided links?

**Comment by xjcvip007** [comment]
Yes, I can't access OneDrive links, even I can access google....

**Comment by wondervictor** [comment]
You can download the models from Baidu Drive now:

| Model | Link | password |
|:--:|:--:|:--:|
| HR18-COFW.pth | https://pan.baidu.com/s/1pV_P-fKY_Ec6pLG8KBt4Iw | prpr |
| HR18-300W.pth | https://pan.baidu.com/s/1Mt-9ZIOrwYb0qN-322kQgg | thwk |
| HR18-AFLW.pth | https://pan.baidu.com/s/18Cwed7hlw8CLeArlSivOeg |  9rtd |
| HR18-WFLW.pth | https://pan.baidu.com/s/1rw7792j6yHoyve55GRx_uA | nvg3 |

**Comment by xjcvip007** [comment]
Wow, thx for your sharing~

**Comment by wondervictor** [comment]
and processed annotations files `data.zip`

|Link|Password|
|:--:|:--:|
|https://pan.baidu.com/s/1UIjq2-uQNLriglhRCGVdNw|96j2|

**Comment by BeierZhu** [comment]
> You can download the models from Baidu Drive now:
> 
> Model	Link	Password
> HR18-COFW.pth	https://pan.baidu.com/s/1pV_P-fKY_Ec6pLG8KBt4Iw	prpr
> HR18-300W.pth	https://pan.baidu.com/s/1S0kKa8bZikr4cocApPxItg	2mgf
> HR18-AFLW.pth	https://pan.baidu.com/s/18Cwed7hlw8CLeArlSivOeg	9rtd
> HR18-WFLW.pth	https://pan.baidu.com/s/1rw7792j6yHoyve55GRx_uA	nvg3

Hi, the link of COFW model seems to be 300W model, could you provide the correct link?
