### ISSUE TITLE
what is the mean of "center" and "scale" in face_landmarks_300w_test.csv

### ISSUE THREAD

**Issue by lakehui** [HRNet/HRNet-Facial-Landmark-Detection#3]
I mean, how do you get the "center_w", "center_h" and "scale"?

**Comment by husencd** [comment]
scale = max(w, h) / 200
center_w = (x1 + x2) / 2
center_h = (y1 + y2) / 2

**Comment by lakehui** [comment]
got it, thanks a lot!

**Comment by vedenev** [comment]
what is w, h, x1, x2, y1, y2 ? in:
scale = max(w, h) / 200
center_w = (x1 + x2) / 2
center_h = (y1 + y2) / 2

**Comment by vincentwei0919** [comment]
the same quention:
what is w, h, x1, x2, y1, y2 ? in:
scale = max(w, h) / 200
center_w = (x1 + x2) / 2
center_h = (y1 + y2) / 2

**Comment by vincentwei0919** [comment]
@lakehui 
could you please tell me about the meaning of those symbols?

**Comment by lakehui** [comment]
> @lakehui
> could you please tell me about the meaning of those symbols?

(x1,y1), (x2,y2) is the coordinates of face bounding box. 
w, h is the width and height of face bounding box.

**Comment by jamesandrewpohadi** [comment]
@lakehui 
I calculate scale, center_w, center_h with:

> (x1,y1), (x2,y2) is the coordinates of face bounding box.
> w, h is the width and height of face bounding box.

However, I get different results..

list_98pt_rect_attr_train.txt:
![Screenshot from 2019-06-06 10-58-20](https://user-images.githubusercontent.com/32510504/59004158-53b7f400-884b-11e9-8338-f5682ccbc8f0.png)
- scale: 0.475
- center_w: 608
- center_h: 128

![Screenshot from 2019-06-06 10-59-24](https://user-images.githubusercontent.com/32510504/59004162-574b7b00-884b-11e9-99dc-ba15bb44946c.png)
- scale: 0.445
- center_w: 518
- center_h: 132

![Screenshot from 2019-06-06 11-00-00](https://user-images.githubusercontent.com/32510504/59004167-5adf0200-884b-11e9-851d-93215df8d5ce.png)
- scale: 0.77
- center_w: 416.5
- center_h: 189.5

vs

face_landmarks_wlfw_train.csv:
![Screenshot from 2019-06-06 10-55-39](https://user-images.githubusercontent.com/32510504/59004157-50246d00-884b-11e9-97ab-a8d6b32e55c7.png)

**Comment by testingshanu** [comment]
May I know why the value is divided by 200? 
Any reason or just a scaling factor?

**Comment by jamesandrewpohadi** [comment]
> @lakehui , @wondervictor
> I calculate scale, center_w, center_h with:
> 
> > (x1,y1), (x2,y2) is the coordinates of face bounding box.
> > w, h is the width and height of face bounding box.
> 
> However, I get different results
> 
> list_98pt_rect_attr_train.txt:
> ![Screenshot from 2019-06-06 10-58-20](https://user-images.githubusercontent.com/32510504/59004158-53b7f400-884b-11e9-8338-f5682ccbc8f0.png)
> 
> * scale: 0.475
> * center_w: 608
> * center_h: 128
> 
> ![Screenshot from 2019-06-06 10-59-24](https://user-images.githubusercontent.com/32510504/59004162-574b7b00-884b-11e9-99dc-ba15bb44946c.png)
> 
> * scale: 0.445
> * center_w: 518
> * center_h: 132
> 
> ![Screenshot from 2019-06-06 11-00-00](https://user-images.githubusercontent.com/32510504/59004167-5adf0200-884b-11e9-851d-93215df8d5ce.png)
> 
> * scale: 0.77
> * center_w: 416.5
> * center_h: 189.5
> 
> vs
> 
> face_landmarks_wlfw_train.csv:
> ![Screenshot from 2019-06-06 10-55-39](https://user-images.githubusercontent.com/32510504/59004157-50246d00-884b-11e9-97ab-a8d6b32e55c7.png)

I figure it out! The bounding box is the smallest box so that all the facial landmarks is in the box (**not the bounding box from "list_98pt_rect_attr_train.txt"**).

For instance,

**(x1,y1),(x2,y2) = (min x, min y), (max x, max y)**

![image](https://user-images.githubusercontent.com/32510504/60440539-99e45580-9c47-11e9-8419-20adcef12e67.png)

**Comment by hao-qiang** [comment]
lmks = lmks.reshape(-1, 2)
x1 = np.min(lmks[:, 0]); x2 = np.max(lmks[:, 0])
y1 = np.min(lmks[:, 1]); y2 = np.max(lmks[:, 1])

scale = max(x2 - x1 + 1, y2 - y1 + 1) / 200
center_w = (x2 + x1) / 2
center_h = (y2 + y1) / 2
