### ISSUE TITLE
HRNET in human pose estimation

### ISSUE THREAD

**Issue by li19960612** [HRNet/HRNet-Facial-Landmark-Detection#32]
Do you ever do some experiments with HRNetv2 or HRNetv2p in human pose estimation? Does it have some improvements?

**Comment by wondervictor** [comment]
see [Higher-HRNet-Human-Pose-Estimation](https://github.com/HRNet/Higher-HRNet-Human-Pose-Estimation) and [HRNet-Human-Pose-Estimation](https://github.com/HRNet/HRNet-Human-Pose-Estimation)
[Deep High-Resolution Representation Learning for Visual Recognition
](https://arxiv.org/abs/1908.07919) provides more details
