### ISSUE TITLE
[demo] for own dataset

### ISSUE THREAD

**Issue by AlexHu123** [HRNet/HRNet-Facial-Landmark-Detection#35]
Thanks for your great job!
Would it be possible for you to inform me about how I should config test.py if I only want to extract facial landmark in my own dataset.
Thanks in advance !

**Comment by wondervictor** [comment]
1. preprocessing your input image according to our preprocessing procedures (e.g. normalize...)
2. load model weights
3. forward model with input images
4. post-processing results (heatmap -> landmarks)

**Comment by 738654805** [comment]
@wondervictor It would be nice of your team to provide the code for visualization.It will facilitate the research. Thx in advance.

**Comment by AlexHu123** [comment]
Thanks for your reply~
