### ISSUE TITLE
About Inference Time

### ISSUE THREAD

**Issue by starhiking** [HRNet/HRNet-Facial-Landmark-Detection#48]
When I run tools/test.py with WFLW dataset , It may cost 115s on single 2080Ti, 85s on 4 2080Tis.
And the CPU cost is high with 300% , but gpu always cost 0% and gpu-memory is very low even though set batchsize as 256.

So It is working fine? If not, can u tell me how to do with it.

**Comment by starhiking** [comment]
Can you share your train time and test time in one-epoch's data

**Comment by wondervictor** [comment]
We've provided training and testing logs in this issue #4
