### ISSUE TITLE
About AFLW dataset 

### ISSUE THREAD

**Issue by starhiking** [HRNet/HRNet-Facial-Landmark-Detection#49]
I download AFLW dataset from someone baiduyun link,maybe the some images is broken.
And when I train the model,Warning message :

`TiffImagePlugin.py:754: UserWarning: Possibly corrupt EXIF data.  Expecting to read 19660800 bytes but only got 0. Skipping tag 0`
  ` " Skipping tag %s" % (size, len(data), tag))`
`PIL/TiffImagePlugin.py:771: UserWarning: Corrupt EXIF data.  Expecting to read 12 bytes but only got 6. 
`

I don't know wheather the image in native dataset is OK.
Have you ever come across the same situation , I wanna ensure wheather the baiduyun_dataset is the same with native one.

**Comment by yangyangkiki** [comment]
We meet a similar warning.
