### ISSUE TITLE
what's the meaning of pose-processing?

### ISSUE THREAD

**Issue by jiangtaoo2333** [HRNet/HRNet-Facial-Landmark-Detection#58]
# pose-processing
    for n in range(coords.size(0)):
        for p in range(coords.size(1)):
            hm = output[n][p]
            px = int(math.floor(coords[n][p][0]))
            py = int(math.floor(coords[n][p][1]))
            if (px > 1) and (px < res[0]) and (py > 1) and (py < res[1]):
                # diff = torch.Tensor([hm[py - 1][px] - hm[py - 1][px - 2], hm[py][px - 1]-hm[py - 2][px - 1]])
                diff = torch.Tensor([hm[py][px + 1] - hm[py][px - 1], hm[py + 1][px]-hm[py - 1][px]])
                coords[n][p] += diff.sign() * .25
    coords += 0.5

so damn hard to understand........ can someone help me????

**Comment by lzcomeon** [comment]
yeah, same questions to me. Have you solved this problem?

**Comment by yinguobing** [comment]
Looks like some kind of interpolation. The authors had mentioned this in their paper:

> At testing, each keypoint location is predicted by transforming the highest heat value location from 1/4 to the original image space and adjusting it with a quarter offset in the direction from the highest response to the second highest response.

**Comment by jiangtaoo2333** [comment]
@yinguobing very 3q.wish good people live longer.

**Comment by lzcomeon** [comment]
> @yinguobing very 3q.wish good people live longer.

What a lovely reply, bro.
