### ISSUE TITLE
Hello, would you like to share the codes for computing AUC?

### ISSUE THREAD

**Issue by Sierkinhane** [HRNet/HRNet-Facial-Landmark-Detection#6]

**Comment by yangyangkiki** [comment]
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import simps

def AUCError(errors, failureThreshold=0.08, step=0.0001, showCurve=False):
    nErrors = len(errors)
    xAxis = list(np.arange(0., failureThreshold + step, step))

    ced =  [float(np.count_nonzero([errors <= x])) / nErrors for x in xAxis]

    AUC = simps(ced, x=xAxis) / failureThreshold
    failureRate = 1. - ced[-1]

    print("AUC @ {0}: {1}".format(failureThreshold, AUC))
    print("Failure rate: {0}".format(failureRate))

    if showCurve:
        plt.plot(xAxis, ced)
        plt.show()

**Comment by kshashankrao** [comment]
May I know, What does errors denote in this context?
Thank you

**Comment by yangyangkiki** [comment]
@kshashankrao 
Hi, errors is a list that save the mean error of each face image. And the mean error is defined as the average Euclidean distance between the predicted facial landmark locations pi,j and their corresponding ground truth facial landmark locations gi,j. 
eg. the test size of COFW dataset is 507, so the length of errors of COFW test set is 507.

**Comment by kshashankrao** [comment]
Hey, thank you for the information. I believe that euclidean distance is calculated by compute_nme function. Should these values be used for AUC or failure (with threshold)?

**Comment by yangyangkiki** [comment]
@kshashankrao 
Hi, you're right. compute_nme function is used to calculate the normalised mean error of a face image. you can save them and then use them to calculate AUC and failure rate (with threshold 0.1 or 0.08).
