### ISSUE TITLE
300W pretrained model weights' name inconsistent with updated model 

### ISSUE THREAD

**Issue by ZhangYuef** [HRNet/HRNet-Facial-Landmark-Detection#78]
Similar problem as issue #5 . Test script is  ` python tools/test.py --cfg experiments/300w/face_alignment_300w_hrnet_w18.yaml --model-file hrnetv2_pretrained/HR18-300W.pt`.

and get following error:
![image](https://user-images.githubusercontent.com/20250982/115369253-c8188980-a17c-11eb-9faf-1bb41f0c6339.png)

**Comment by pablocael** [comment]
Im also having the same problem. Anyone can give a little help? Thanks

**Comment by nnizhang** [comment]
You can modify tools/test.py as follows.

 ### original test.py (line 59-65)

    state_dict = torch.load(args.model_file)
    if 'state_dict' in state_dict.keys():
        state_dict = state_dict['state_dict']
        model.load_state_dict(state_dict)
    else:
        model.module.load_state_dict(state_dict)

 ### modifying original test.py to:
    state_dict = torch.load(args.model_file)
    from collections import OrderedDict

    new_state_dict = OrderedDict()
    for k, v in state_dict.items():
        name = k[7:]  # remove `module.`
        new_state_dict[name] = v
    model.module.load_state_dict(new_state_dict)

**Comment by ZhangYuef** [comment]
> You can modify tools/test.py as follows.
> 
> ### original test.py (line 59-65)
> ```
> state_dict = torch.load(args.model_file)
> if 'state_dict' in state_dict.keys():
>     state_dict = state_dict['state_dict']
>     model.load_state_dict(state_dict)
> else:
>     model.module.load_state_dict(state_dict)
> ```
> 
> ### modifying original test.py to:
> ```
> state_dict = torch.load(args.model_file)
> from collections import OrderedDict
> 
> new_state_dict = OrderedDict()
> for k, v in state_dict.items():
>     name = k[7:]  # remove `module.`
>     new_state_dict[name] = v
> model.module.load_state_dict(new_state_dict)
> ```

Thanks for reply. The problem happens because the pretrained model is on distribution setting so there is a 'module' keyword in `state_dict`.
