### ISSUE TITLE
How to download the 300W full set?

### ISSUE THREAD

**Issue by XYZ-qiyh** [HRNet/HRNet-Facial-Landmark-Detection#89]
@sunke123 @yangyangkiki 
Hello, thanks for your amazing project.
My question is how to download the **300W full set**. The official 300W test set is provided by [here](https://ibug.doc.ic.ac.uk/resources/300-W/). 
But I can't find the link to download the **300W full set**. However, the evaluation results are usually carried on **300W full set** (common/challenging/full).

Looking forward to your reply, many thanks!

**Comment by yangyangkiki** [comment]
Hi, I am not sure whether it is publicly available now. I recommend you email the dataset owners to request the full set.

**Comment by XYZ-qiyh** [comment]
> Hi, I am not sure whether it is publicly available now. I recommend you email the dataset owners to request the full set.

Thanks for your reply. I'll try it later.
