### ISSUE TITLE
I want to detect landmarks in real time

### ISSUE THREAD

**Issue by MujoNoThuki** [HRNet/HRNet-Facial-Landmark-Detection#90]
hello.
I was able to use this system to train and infer models.
I use "final_state.pth" for the model file.
How can I edit "tool/test.py" to make a program that detects landmarks by putting images taken by a webcam into the model in real time? Or do you have such a program?

**Comment by kanybekasanbekov** [comment]
https://github.com/HRNet/HRNet-Facial-Landmark-Detection/issues/91
